# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-09 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0017_auto_20170918_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='data_tramitacao',
            field=models.DateTimeField(verbose_name='Data Tramitação'),
        ),
    ]
