# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-01-11 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0021_auto_20180103_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomaterialegislativa',
            name='sequencia_numeracao',
            field=models.CharField(blank=True, choices=[('A', 'Sequencial por ano'), ('L', 'Sequencial por legislatura'), ('U', 'Sequencial único')], max_length=1, null=True, verbose_name='Sequência de numeração'),
        ),
    ]
