# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-13 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0015_sessaoplenaria_painel_aberto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessaoplenaria',
            options={'ordering': ('-data_inicio',), 'verbose_name': 'Sessão Plenária', 'verbose_name_plural': 'Sessões Plenárias'},
        ),
    ]
