# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-09 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0002_remove_documentoadministrativo_numero_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacaoadministrativo',
            name='data_tramitacao',
            field=models.DateTimeField(verbose_name='Data Tramitação'),
        ),
    ]
